/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import java.util.Collections;
import javax.swing.JOptionPane;
import java.util.Timer;
import java.util.TimerTask;

/**
 *
 * @author ssuyuanhuang
 */
public class HappyStar extends javax.swing.JFrame {
Connection conn =new DBConnection().connect();
String userAnswer,bestAnswer,myNickname;
int question_no=0,sqlQuestion_id=0,myUserid=0,myMoney=50,sec=20;
Timer timer=new Timer();
TimerTask task=new TimerTask()
{
    public void run()
    {
        jSec.setText("剩餘秒數："+sec);
        if(sec==0){
            if(jTextField1.getText().equals("")){
                jTextField1.setText("0");
            }
            if(jTextField2.getText().equals("")){
                jTextField2.setText("0");
            }
            if(jTextField3.getText().equals("")){
                jTextField3.setText("0");
            }
            int ans_money1 = Integer.parseInt(jTextField1.getText());
            int ans_money2 = Integer.parseInt(jTextField2.getText());
            int ans_money3 = Integer.parseInt(jTextField3.getText());
            checkAnswer(jLabel4.getText(),question_no,ans_money1);
            checkAnswer(jLabel5.getText(),question_no,ans_money2);
            checkAnswer(jLabel6.getText(),question_no,ans_money3);
            jTextField1.setText("");
            jTextField2.setText("");
            jTextField3.setText("");
            int ans_money_total=(ans_money1+ans_money2+ans_money3);
            if(ans_money_total>myMoney){
                ans_money1 = 0;
                ans_money2 = 0;
                ans_money3 = 0;
            }
            if((question_no>=5)||(myMoney<=0)){//超過5題或所剩金額小於等於，0結算成績
                stoptimer();
                int saveMoney=myMoney*10000;
                SaveMoneyInformation(saveMoney);
                MainMenu mm= new MainMenu(myUserid);
                mm.show();
            }else{
                nextquestion();
            }             
        }
    sec--;
    }
};
    /**
     * Creates new form Million
     */
        public HappyStar(int userid,String nickname) {
            initComponents();
            jLabel1.setText("歡迎挑戰者："+nickname+"，加油加油加油！");
            myUserid=userid;
            myNickname=nickname;
            nextquestion();
            timer.scheduleAtFixedRate(task, sec, 1000);
        }

    private HappyStar() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSec = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(860, 550));
        setMinimumSize(new java.awt.Dimension(860, 550));
        setPreferredSize(new java.awt.Dimension(612, 512));
        setResizable(false);
        setSize(new java.awt.Dimension(612, 512));

        jLabel1.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        jLabel1.setText("歡迎");

        jSec.setFont(new java.awt.Font("微軟正黑體", 0, 36)); // NOI18N
        jSec.setText("剩餘時間");

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("華康中黑體", 0, 36)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setEnabled(false);
        jTextArea1.setSelectionColor(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(jTextArea1);

        jButton4.setText("逃離戰場");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("微軟正黑體", 0, 24)); // NOI18N
        jLabel4.setText("A");

        jTextField1.setFont(new java.awt.Font("新細明體", 0, 18)); // NOI18N

        jLabel3.setText("下注金額：萬元為單位，若下注1萬，請輸入1");

        jTextField2.setFont(new java.awt.Font("新細明體", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("微軟正黑體", 0, 24)); // NOI18N
        jLabel5.setText("B");

        jTextField3.setFont(new java.awt.Font("新細明體", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("微軟正黑體", 0, 24)); // NOI18N
        jLabel6.setText("C");

        jLabel8.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        jLabel8.setText("萬");

        jLabel9.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        jLabel9.setText("萬");

        jLabel10.setFont(new java.awt.Font("微軟正黑體", 0, 18)); // NOI18N
        jLabel10.setText("萬");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel9)))
                        .addGap(100, 100, 100)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel10)))
                        .addGap(3, 3, 3))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(jLabel3))
        );

        jLabel7.setFont(new java.awt.Font("微軟正黑體", 0, 12)); // NOI18N
        jLabel7.setText("目前剩餘獎金");

        jButton1.setText("確認答案");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("微軟正黑體", 0, 36)); // NOI18N
        jLabel2.setText("題號");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jSec))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 752, Short.MAX_VALUE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(98, 98, 98))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSec)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(58, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        int ExitCheck=JOptionPane.showConfirmDialog(null,"你確定要逃離戰場嗎？(會記錄下來，很丟臉的喔!!)","Are you sure?",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
        if(ExitCheck==0){            
            String sql="insert into anshistory(qus_id,his_million,his_qusno,user_id,his_ans,his_pass) values('"+sqlQuestion_id+"','0','"+question_no+"','"+myUserid+"','"+"((逃離戰場))"+"','0')";//儲存答題紀錄
            try{
            PreparedStatement ps=conn.prepareStatement(sql);
            ps.execute();
            }
            catch (Exception e){
                System.out.println("error"+e);
            }
            stoptimer();
            MainMenu mm= new MainMenu(myUserid);
            mm.show();
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        if(jTextField1.getText().equals("")){
            jTextField1.setText("0");
        }
        if(jTextField2.getText().equals("")){
            jTextField2.setText("0");
        }
        if(jTextField3.getText().equals("")){
            jTextField3.setText("0");
        }
        int ans_money1 = Integer.parseInt(jTextField1.getText());
        int ans_money2 = Integer.parseInt(jTextField2.getText());
        int ans_money3 = Integer.parseInt(jTextField3.getText());
        int ans_money_total=(ans_money1+ans_money2+ans_money3);
        if(ans_money_total<myMoney){
            int moneyCheck=JOptionPane.showConfirmDialog(null,"你下注的金額只有"+ans_money_total+"萬元，剩餘沒下注的錢會被沒收喔！","Are you sure?",JOptionPane.YES_NO_OPTION,JOptionPane.WARNING_MESSAGE);
            if(moneyCheck==0){
                checkAnswer(jLabel4.getText(),question_no,ans_money1);
                checkAnswer(jLabel5.getText(),question_no,ans_money2);
                checkAnswer(jLabel6.getText(),question_no,ans_money3);
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                        if((question_no>=5)||(myMoney<=0)){//超過5題或所剩金額小於等於，0結算成績
                            stoptimer();
                            int saveMoney=myMoney*10000;
                            SaveMoneyInformation(saveMoney);
                            MainMenu mm= new MainMenu(myUserid);
                            mm.show();
                        }else{
                            nextquestion();
                        }
            }
        }else{
               if(ans_money_total>myMoney){
                JOptionPane.showMessageDialog(null,"你目前只有"+myMoney+"萬元，但你下注的金額"+ans_money_total+"萬元，已經超過你的經濟許可了！","你口袋沒這麼深",JOptionPane.ERROR_MESSAGE);
                }else{
                checkAnswer(jLabel4.getText(),question_no,ans_money1);
                checkAnswer(jLabel5.getText(),question_no,ans_money2);
                checkAnswer(jLabel6.getText(),question_no,ans_money3);
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                        if((question_no>=5)||(myMoney<=0)){//超過5題或所剩金額小於等於，0結算成績
                            stoptimer();
                            int saveMoney=myMoney*10000;
                            SaveMoneyInformation(saveMoney);
                            MainMenu mm= new MainMenu(myUserid);
                            mm.show();
                        }else{
                            nextquestion();
                        }
                }
        }

    }//GEN-LAST:event_jButton1ActionPerformed
 
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Million.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Million.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Million.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Million.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HappyStar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jSec;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    // End of variables declaration//GEN-END:variables

    private void nextquestion() {
        String sql;
        if(userAnswer != null && !userAnswer.equals("")){
            sql="select * from question where qus_id NOT IN("+userAnswer+") ORDER BY RAND() LIMIT 0,1";
            System.out.println(sql);
        }else{
            sql="select * from question ORDER BY RAND() LIMIT 0,1"; 
        }
        try{
           PreparedStatement ps=conn.prepareStatement(sql);
           ResultSet rs=ps.executeQuery();
           if(rs.next()){
                question_no++;
                jLabel2.setText("第"+question_no+"題");
                jLabel7.setText("目前剩餘獎金："+myMoney+"萬元");
                sqlQuestion_id=rs.getInt("qus_id");
                String sql_id = Integer.toString(sqlQuestion_id);
                if(userAnswer != null && !userAnswer.equals("")){
                    userAnswer=userAnswer+", '"+sql_id+"'";
                }else{
                    userAnswer="'"+sql_id+"'";
                }
                String subject=rs.getString("qus_subject");
                ArrayList<String> Answer = new ArrayList<>();
                Answer.add(rs.getString("qus_ansA"));
                Answer.add(rs.getString("qus_ansB"));
                Answer.add(rs.getString("qus_ansC"));
                Collections.shuffle(Answer);
                bestAnswer=rs.getString("qus_bestAns");
                jLabel4.setText(Answer.get(0));
                jLabel5.setText(Answer.get(1));
                jLabel6.setText(Answer.get(2));
                jTextArea1.setLineWrap(true);
                jTextArea1.setText(subject);
                sec=20;//設定20秒回答問題
           }else{
               JOptionPane.showMessageDialog(null,"題目取得失敗");
           }
        }
        catch (Exception e){
            System.out.println("error"+e);
        }
    }

    private void checkAnswer(String ThisAnswer,int question_nob,int ans_money) {//檢查點選的答案是否正確
            int saveMoney=ans_money*10000;
            if(bestAnswer.equals(ThisAnswer)){
            String sql="insert into anshistory(qus_id,his_million,his_qusno,user_id,his_ans,his_pass,his_money) values('"+sqlQuestion_id+"','0','"+question_nob+"','"+myUserid+"','"+ThisAnswer+"','1','"+saveMoney+"')";//儲存答題紀錄
            System.out.println(sql);
                try{
                  PreparedStatement ps=conn.prepareStatement(sql);
                   if(ps.execute()){
                       JOptionPane.showMessageDialog(null,"紀錄失敗");
                   }else{
                       System.out.println("紀錄成功");
                       myMoney=ans_money;
                   }
                }
                catch (Exception e){
                    System.out.println("error"+e);
                }
        }else{
            String sql="insert into anshistory(qus_id,his_million,his_qusno,user_id,his_ans,his_money) values('"+sqlQuestion_id+"','0','"+question_no+"','"+myUserid+"','"+ThisAnswer+"','"+saveMoney+"')";
                try{
                  PreparedStatement ps=conn.prepareStatement(sql);
                   if(ps.execute()){
                       JOptionPane.showMessageDialog(null,"紀錄失敗");
                   }else{
                       System.out.println("紀錄成功");
                   }
                }
                catch (Exception e){
                    System.out.println("error"+e);
                }
        }
    }

    private void SaveMoneyInformation(int Award) {
            String sql="insert into moneyhistory(user_id,money_subject,money_inout,money_total) values('"+myUserid+"','2','1','"+Award+"')";
            System.out.println(sql);
                try{
                  PreparedStatement ps=conn.prepareStatement(sql);
                   if(ps.execute()){
                       System.out.println("金錢紀錄失敗");
                   }else{
                       String sql2="update user set user_money=user_money+'"+Award+"' where user_id='"+myUserid+"'";
                       PreparedStatement ps2=conn.prepareStatement(sql2);
                       ps2.execute();
                       System.out.println("金錢紀錄成功");
                    if(Award>0){
                    JOptionPane.showMessageDialog(null,"結算成績，您獲得"+Award+"元獎金！","太棒了",JOptionPane.INFORMATION_MESSAGE);
                    }else{
                    JOptionPane.showMessageDialog(null,"挑戰失敗，一毛錢都沒有！","真可惜",JOptionPane.ERROR_MESSAGE);
                    }
                   }
                }
                catch (Exception e){
                    System.out.println("error"+e);
                }
           
    }

    private void stoptimer() {
        timer.cancel();
        dispose();
    }
    
}